# Generated by Django 5.2.1 on 2025-05-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes_app', '0002_datoprueba_fecha_nac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12)),
                ('fecha_nac', models.DateField(null=True)),
                ('telefono', models.IntegerField(max_length=11)),
                ('telefono_emergencia', models.IntegerField(max_length=11, null=True)),
                ('parentesco_tel_emer', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='datoPrueba',
        ),
    ]
