# Generated by Django 5.2.1 on 2025-05-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes_app', '0003_paciente_delete_datoprueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_emergencia',
            field=models.IntegerField(null=True),
        ),
    ]
