# Generated by Django 5.2.1 on 2025-05-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes_app', '0004_alter_paciente_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
